### ISSUE TITLE
Build broken with ZSH

### ISSUE THREAD

**Issue by johncant** [matplotlib/basemap#362] opened 2017-07-07 15:15 UTC
The build is broken when run inside ZSH due to BASH-specific shell expansions. Workaround:
```
SHELL=/bin/bash python setup.py install
```

Output of `python setup.py install`
```
$ python setup.py install
checking for GEOS lib in /home/john ....
checking for GEOS lib in /home/john/local ....
checking for GEOS lib in /usr ....
GEOS lib (version 3.5.0) found in /usr
/usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib64/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'namespace_packages'
  warnings.warn(msg)
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_geoslib" sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building '_geoslib' extension
compiling C sources
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC

compile options: '-I/usr/include -I['/home/john/src/v3/lib/python3.6/site-packages/numpy/core/include'] -I/home/john/src/v3/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c'
gcc: src/_geoslib.c
zsh:1: no matches found: -I[/home/john/src/v3/lib/python3.6/site-packages/numpy/core/include]
zsh:1: no matches found: -I[/home/john/src/v3/lib/python3.6/site-packages/numpy/core/include]
error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/usr/include -I['/home/john/src/v3/lib/python3.6/site-packages/numpy/core/include'] -I/home/john/src/v3/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c src/_geoslib.c -o build/temp.linux-x86_64-3.6/src/_geoslib.o -MMD -MF build/temp.linux-x86_64-3.6/src/_geoslib.o.d" failed with exit status 1
```

**Comment by WeatherGod** [comment] 2017-07-09 00:52
pull requests are welcomed for fixing this

**Comment by Koff** [comment] 2017-11-19 19:54
Same error for me, the problem is on line 80 of setup.py:

```geos_include_dirs = [os.path.join(GEOS_dir,'include'),inc_dirs]```

Should be: 

```geos_include_dirs = [os.path.join(GEOS_dir,'include'),inc_dirs[0]]```

**Comment by molinav** [comment] 2022-01-02 22:32
With the `basemap` release 1.3.0, there has been a significant refactoring of the library. Among other things, the package has been split in three parts (`basemap`, `basemap-data` and `basemap-data-hires`). The [`setup.py`] file for `basemap` has also been significantly rewritten.

I have tried to run the [`setup.py`] for `basemap` using `zsh` under Ubuntu 20.04 and it built successfully. In addition, for some specific platforms and versions (Windows and GNU/Linux, archs x86 and x64, Python 2.7 and 3.5-3.9) we now offer precompiled binary wheels in PyPI.

It would be great if you can confirm whether or not the problem persists for you. If the problem is gone, I will be glad of marking this issue as solved and close it.

[`setup.py`]:
https://github.com/matplotlib/basemap/blob/v1.3.0/packages/basemap/setup.py

**Closed** 2022-01-07 13:05 UTC
