### ISSUE TITLE
ortho projection cutting off edges

### ISSUE THREAD

**Issue by avipersin** [matplotlib/basemap#412] opened 2018-07-10 17:02 UTC
If you look closely at the left, right, top, and bottom edges of of the plot you will notice the boundary line at the 4 corners is being slightly cut off by 1 pixel.

I am using basemap 1.1.0. I don't recall this being a problem in earlier releases.
```
from mpl_toolkits.basemap import Basemap

bm = Basemap(projection='ortho', lat_0=0, lon_0=0)
bm.drawcoastlines()
plt.show()
```
![figure_1](https://user-images.githubusercontent.com/8727319/42525328-e1456998-8440-11e8-900e-449571d2d865.png)

**Comment by avipersin** [comment] 2018-07-10 18:31
Sorry, it was a typo. I've fixed the original post.

```
bm = Basemap(projection='ortho', lat_0=0, lon_0=0)
```

**Comment by WeatherGod** [comment] 2018-07-10 18:58
duplicate of #344 

It is a result of a new feature in v1.1.0. I haven't figured out how to fix it properly. Closing as this is a duplicate bug report.

**Closed by WeatherGod** 2018-07-10 18:58 UTC
