### ISSUE TITLE
Basemap don't find PROJ_LIB on import

### ISSUE THREAD

**Issue by blaylockbk** [matplotlib/basemap#431] opened 2018-10-17 20:40 UTC
I just did a fresh install of Anaconda 5.7 for Python 3.7. Then I installed Basemap with `conda install -c conda-forge basemap`.

When I import basemap: `from mpl_toolkits.basemap import Basemap` I get the following error:

```
>>> from mpl_toolkits.basemap import Basemap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\u0553130\AppData\Local\Continuum\anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 155, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "C:\Users\u0553130\AppData\Local\Continuum\anaconda3\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```

**Comment by QuLogic** [comment] 2018-10-17 21:42
Duplicate of #419. This is a conda-forge issue.

**Closed by QuLogic** 2018-10-17 21:42 UTC
