### ISSUE TITLE
wmsimage() Error AttributeError: 'ResponseWrapper' object has no attribute 'url'

### ISSUE THREAD

**Issue by danhamill** [matplotlib/basemap#318] opened 2016-09-23 16:29 UTC
On my window machine I can use the following script to connect to a wms server:

```
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt


#map bounds
min_lon = -111.8007170968785
max_lon = -111.79885067564109
min_lat = 36.194658377025071
max_lat = 36.200643218289684

fig = plt.figure()
ax = fig.add_subplot(111)
m = Basemap(projection='merc', 
            epsg=cs2cs_args.split(':')[1], 
            llcrnrlon=(min_lon- 0.0007), 
            llcrnrlat=(min_lat - 0.0006),
            urcrnrlon=(max_lon + 0.0005), 
            urcrnrlat=(max_lat + 0.0006))
m.wmsimage(server='http://grandcanyon.usgs.gov/arcgis/services/Imagery/ColoradoRiverImageryExplorer/MapServer/WmsServer?', layers=['1'], xpixels=1000)
plt.show()
```

However, when I try to connect on my UNIX machine I get the following error:
```
AttributeError: 'ResponseWrapper' object has no attribute 'url'
```
A little bit about my windows machine

```
             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.20.0
       python version : 2.7.11.final.0

```
relevant libraries:
```
matplotlib                                                 1.5.1               np110py27_0
basemap (from mpl_toolkits)                   1.0.8                     <pip>
OWSLib                                                    0.11.2                    <pip>
 ```
and my unix machine:

```
owslib 0.12.0
matplotlib 1.5.1
basemap (from mpl_toolkits) 1.0.6
Fedora 20
python 2.7.5
```

**Comment by WeatherGod** [comment] 2016-09-23 16:35
Duplicate of #259 and fixed therein. Either downgrade owslib or install basemap from the master branch which has the fix.

I am currently working on getting the packaged data fixed so that I can put out a new release, but I am running into issues with the updated data.

**Closed** 2016-09-23 16:35 UTC
