### ISSUE TITLE
six<1.16 requirement

### ISSUE THREAD

**Issue by ijdbuser** [matplotlib/basemap#545] opened 2022-06-08 01:27 UTC
Please upgrade to 1.16+

**Comment by molinav** [comment] 2022-06-08 06:34
Hi @ijdbuser! This would be a duplicate of #536, which is already solved. Starting with `basemap` 1.3.3, `six` was removed from the dependencies. You can update to this version and then `basemap` will not cause conflicts about the `six` version.

**Closed** 2022-06-08 11:32 UTC
