### ISSUE TITLE
failed with exit status 127

### ISSUE THREAD

**Issue by slarkhe** [matplotlib/basemap#461] opened 2019-04-23 13:38 UTC
/home/hsz/software/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/home/hsz/software/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'namespace_packages'
  warnings.warn(msg)
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_geoslib" sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building '_geoslib' extension
compiling C sources
C compiler: x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/hsz/software/netcdf4/include -fPIC

compile options: '-Iinclude -I/home/hsz/software/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/hsz/software/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/hsz/software/anaconda3/include/python3.6m -c'
x86_64-conda_cos6-linux-gnu-gcc: src/_geoslib.c
error: Command "x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/hsz/software/netcdf4/include -fPIC -Iinclude -I/home/hsz/software/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/hsz/software/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/hsz/software/anaconda3/include/python3.6m -c src/_geoslib.c -o build/temp.linux-x86_64-3.6/src/_geoslib.o -MMD -MF build/temp.linux-x86_64-3.6/src/_geoslib.o.d" failed with exit status 127

**Comment by QuLogic** [comment] 2019-04-23 18:58
You need to install the compiler in conda.

**Comment by slarkhe** [comment] 2019-04-23 23:15
thanks,  what is the compiler's name?I don't know how to install it   



            
            
                
                    
                            
                                
                            
                            
                                fio_szhe
                            
                    
                        
                            
                                    邮箱：fio_szhe@fio.org.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 04/24/2019 02:58, Elliott Sales de Andrade wrote: You need to install the compiler in conda.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/matplotlib/basemap","title":"matplotlib/basemap","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/matplotlib/basemap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@QuLogic in #461: You need to install the compiler in conda."}],"action":{"name":"View Issue","url":"https://github.com/matplotlib/basemap/issues/461#issuecomment-485931964"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/matplotlib/basemap/issues/461#issuecomment-485931964",
"url": "https://github.com/matplotlib/basemap/issues/461#issuecomment-485931964",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by slarkhe** [comment] 2019-04-24 00:20
> You need to install the compiler in conda.

thanks,  but I  don't know what is the compiler's name? and how to install it  ？

**Comment by slarkhe** [comment] 2019-04-24 01:56
> You need to install the compiler in conda.

my lunix system：centos6

**Comment by summerinternship2019** [comment] 2019-09-02 23:22
I got the same error message 
and stack this installation 
which compiler you talk about??

**Comment by slarkhe** [comment] 2019-09-11 12:57
the version of matplotlib is too new ，you can try  matplotlib3.0 or older 

2019-09-03 07:22:38Miguel <notifications@github.com>写道：

I got the same error message
and stack this installation
which compiler you talk about??

**Comment by dbricare** [comment] 2020-09-18 22:04
For me the cause was no gcc installed. On Ubuntu `sudo apt install gcc` resolved the exception.

**Comment by molinav** [comment] 2021-12-29 12:55
We have just released `basemap` version 1.3.0 with precompiled binary wheels for Windows and GNU/Linux, so you do not need to compile the library by yourself anymore on these platforms.

I am closing this issue now. Feel free to open a new one or write here if the problems persist.

**Closed by molinav** 2021-12-29 12:55 UTC
