### ISSUE TITLE
unable to give latitude and longitude to the basemap

### ISSUE THREAD

**Issue by haritha1022** [matplotlib/basemap#556] opened 2022-10-14 09:14 UTC
I was trying to plot argoflots data  they are situated at same latitude and longitude with little variation i want know exact location of each argofloat
![argo](https://user-images.githubusercontent.com/97615200/195808866-adc8ad82-df16-4b30-9454-a7a83571b76c.png)

here is the code:
df = pd.read_csv("Book122.csv")

plt.figure(figsize=((19,10)))

x=df['longitude']
y=df['latitude']

m = Basemap(projection='cyl',llcrnrlat=27.1022,urcrnrlat=27.1025,\
        llcrnrlon=64.7793,urcrnrlon=64.7799,resolution='h')

m.scatter(x,y,zorder=10)
m.drawparallels(np.arange(int(27.101),int(27.103),0.001),labels=[1,0,0,0])
m.drawmeridians(np.arange(int(64.7791),int(64.7798),0.0001),labels=[0,0,0,1])
#m.drawcoastlines()
m.fillcontinents(color='white')
m.drawmapboundary()

plt.show()

**Comment by guziy** [comment] 2022-10-15 10:20
The problem is that 

```python
int(64.7791) == int(64.7798) == 64
```
same thing for longitudes. So your `np.arange` returns an empty array.

```python
In [2]: np.arange(int(64.7791),int(64.7798),0.0001)
Out[2]: array([], dtype=float64)
```

**Comment by molinav** [comment] 2022-10-17 16:50
This looks more like a support problem and not a bug in `basemap`. Since @guziy identified and described the problem in the code snippet, I think we can close this issue.

**Closed by molinav** 2022-10-17 16:50 UTC
